### ISSUE TITLE
System.NullReferenceException calling ReInitializeAllTextboxes()

### ISSUE THREAD

**Issue by JoNMii** [NLog/NLog.Windows.Forms#67]
It is working on the Test project on this repo, however i copied exactly all the code to my project and i get this error.,

https://imgur.com/a/ak9gJzM

**Comment by 304NotModified** [comment]
I guess your nlog.config is not valid or not published.

Please check if `LogManager.Configuration` is not null.

The error is not that good, will try to improve that

**Comment by 304NotModified** [comment]
(Please also post code and not images of code. )

**Comment by 304NotModified** [comment]
fixed by #72

**Comment by JoNMii** [comment]
Hi,

Thanks for your reply. It seems you were right. I forget to add "Copy in build" setting to the Nlog conf file.
Anyway, with the latest version you still get the same exception. It would be nice some message saying that conf file is missing or smth.

Thanks!

**Comment by 304NotModified** [comment]
It should say with version 4.4 that the config is missing. Tested it locally also.
